// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN_4IePITNubsMXqA09n4aMDwrRk_Cg0U',
    appId: '1:209688556274:web:9806c3c43ad81693b6566b',
    messagingSenderId: '209688556274',
    projectId: 'pratnotes',
    authDomain: 'pratnotes.firebaseapp.com',
    storageBucket: 'pratnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbb4pPVlwkOmzJagQg7ef6TnJatSYCuRo',
    appId: '1:209688556274:android:fb38da50b90bb205b6566b',
    messagingSenderId: '209688556274',
    projectId: 'pratnotes',
    storageBucket: 'pratnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhm-qCRai89JaZfxhvgbAoiaw1d1xD2yA',
    appId: '1:209688556274:ios:d6eb06f31def72d1b6566b',
    messagingSenderId: '209688556274',
    projectId: 'pratnotes',
    storageBucket: 'pratnotes.appspot.com',
    iosBundleId: 'com.yadayada.pratnotes',
  );
}
